version: '3'

services:
  web:
    image: webdevops/php-apache-dev:7.1
    container_name: tasks_web
    working_dir: /var/www/html/tasks.loc
    environment:
      WEB_DOCUMENT_ROOT: /var/www/html/tasks.loc/public
      PHP_DISPLAY_ERRORS: 1
    ports:
      - 8000:80
    volumes:
      - ./public:/var/www/html/tasks.loc/public
      - ./src:/var/www/html/tasks.loc/src
      - ./vendor:/var/www/html/tasks.loc/vendor
    links:
      - db

  db:
    image: mysql:5.6
    container_name: tasks_db
    ports:
      - 33060:3306
    environment:
      MYSQL_DATABASE: tasks_db
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./data:/var/lib/mysql
